### ISSUE TITLE
make item codes available through constants (similar to class.go)

### ISSUE THREAD

**Issue by jordanbrauer** [nokka/d2s#17]
Hello there! I will start by saying, great job on this lib! I do not personally play on the slash servers (though did at one point many years ago), but do play single player and have always been fascinated with Diablo II save & item files.

Your library is what I chose to use for my own pet project and as I used it, I noticed that many types & constants are not exported for consumer use. I would like to propose a change for this! To start, I feel that exposing item codes as named constants would make for good dev experience for both contributors & consumers. For (a silly) example, we can reference & check the `item.Type` field against a nice constant, such as the obscure zweihander code `9fb` among many many others,

```go
func isZweihander(item d2s.Item) bool {
    return d2s.Zweihander == item.Type
}
```

This is particularly nice & useful for other files, variables, and constants that need to use the item type codes (such as [`socketables.go`](https://github.com/nokka/d2s/blob/master/socketables.go), and the `item.go` variables [`weaponDamageMap`](https://github.com/nokka/d2s/blob/master/item.go#L106-L108) and [`quantityMap`](https://github.com/nokka/d2s/blob/master/item.go#L491-L493), etc), preventing duplication and accidental typos by providing autocomplete if your editor/IDE supports it, especially as new bits are decoded and this package continues to grow.

I see that you already have the same pattern in [the `class.go` file](https://github.com/nokka/d2s/blob/master/class.go#L5-L24).

Will be interested to hear what you think. If you'd like, I also already have a branch on a fork that I can submit as PR for review, as I needed this for my own project. 🙂

**Comment by nokka** [comment]
Hello, thanks for your input, this started as a pet project of my own to learn Go back in 2016, I've been working with it professionally and on my spare time since then so this project could definitely use some refactoring to meet the demands of people now that it's being used for more than just the Slashdiablo armory. I recently extended the [public API](https://github.com/nokka/d2s/commit/39035247e1b856d636b1c8b8b6e3213435cf88b8) a bit because I needed to access some things in a consumer project of the library so I think your proposed changes would make a great addition.

What did you have in mind, just all the codes as constants and then refactor to use them for things such as the weapon type [map](https://github.com/nokka/d2s/blob/master/item.go#L106)? 

Make a pull request if you want to merge your forked changes and let's have a look!

**Comment by jordanbrauer** [comment]
> What did you have in mind

I have a few ideas, but to start I think that refactoring item codes will be one PR. I will open a new issue & PR after this one, but all the ideas I have would work towards making a good developer experience – both contributing to and consuming this package. I'll put details in a new issue & PR though. 

> Make a pull request if you want to merge your forked changes and let's have a look!

👍 Sounds great – will submit that right away!

**Comment by mgamperl** [comment]
Hi,
I am using this awesome library for a tool I'm developing (Plugy Item Sorter and Holy Grail List) and I really much like the idea of the refactoring of items codes to constants.

In fact I have some code ready in my own branch / my own repo which I could provide if you guys are interested.
It is based on @jordanbrauer s merge request but I added / fixed some things using information available on the web or from d2data ( (like correct TypeNames, sizes, ..)

Here are some examples of what it looks like

ItemTypes with typed constants:
```golang
type ItemType string

// Item code value constant used as an internal reference or "ID".
const (
	// Armor
	AlphaHelm         ItemType = "dr6"
	AncientArmor      ItemType = "aar"
	Antlers           ItemType = "dr3"
	ArchonPlate       ItemType = "utp"
	Armet             ItemType = "ulm"
	AssaultHelmet     ItemType = "ba4"
	AvengerGuard      ItemType = "ba5"
```

Unique Item List:
```golang
var UniqueItems = map[uint64]UniqueItem{
	0:   {ItemType: d2s.HandAxe, Name: "The Gnasher"},
	1:   {ItemType: d2s.Axe, Name: "Deathspade"},
	2:   {ItemType: d2s.DoubleAxe, Name: "Bladebone"},
	3:   {ItemType: d2s.MilitaryPick, Name: "Mindrend"},
	4:   {ItemType: d2s.WarAxe, Name: "Rakescar"},
```

Set Item List
```golang
var SetItems = map[uint64]SetItem{
	0:   {ItemType: d2s.LargeShield, SetName: "Civerb's Vestments", Name: "Civerb's Ward"},
	1:   {ItemType: d2s.Amulet, SetName: "Civerb's Vestments", Name: "Civerb's Icon"},
	2:   {ItemType: d2s.GrandScepter, SetName: "Civerb's Vestments", Name: "Civerb's Cudgel"},
	3:   {ItemType: d2s.ChainBoots, SetName: "Hsarus' Defense", Name: "Hsaru's Iron Heel"},
	4:   {ItemType: d2s.Buckler, SetName: "Hsarus' Defense", Name: "Hsaru's Iron Fist"},
```

Also some additonal item information based on the type (the categories are not final yet, I have to put more thought into this but `ItemQuality` and `SizeX` and `SizeY` I could provide now.
```golang
var itemPropertyMap = map[d2s.ItemType]*ItemPropertyData{
           // War Hammer
	d2s.Maul:                          {ItemQuality: ItemQualityNormal, SizeX: 2, SizeY: 4, ItemCategory: Weapons, ItemSubCategory: HammersAndMaces, ItemSubSubCategory: Hammers},              // Maul
	d2s.GreatMaul:                     {ItemQuality: ItemQualityNormal, SizeX: 2, SizeY: 3, ItemCategory: Weapons, ItemSubCategory: HammersAndMaces, ItemSubSubCategory: Hammers},              // Great Maul
	d2s.Cudgel:                        {ItemQuality: ItemQualityExceptional, SizeX: 1, SizeY: 3, ItemCategory: Weapons, ItemSubCategory: HammersAndMaces, ItemSubSubCategory: Maces},           // Cudgel
	d2s.BarbedClub:                    {ItemQuality: ItemQualityExceptional, SizeX: 1, SizeY: 3, ItemCategory: Weapons, ItemSubCategory: HammersAndMaces, ItemSubSubCategory: Maces},  
```
Let me know if you would accept a merge request then I will put more work into it otherwise I will keep this in my own fork.
